### ISSUE TITLE
使用该主题模板时，building过程中卡住

### ISSUE THREAD

**Issue by JQiue** [Mister-Hope/vuepress-theme-hope-template#67]
yarn 1.22.4
node 11.11.0
请求帮助

**Comment by Mister-Hope** [comment]
> yarn 1.22.4
> node 11.11.0
> 请求帮助

给个demo呗？CI自动部署现在是没问题的，我先吃个饭，吃完马上给你看hhh

**Comment by JQiue** [comment]
demo就是clone的这个主题模板，然而执行yarn run serve时，building总是卡在40%

**Comment by Mister-Hope** [comment]
> demo就是clone的这个主题模板，然而执行yarn run serve时，building总是卡在40%

等会，咋还在用11，有啥特殊需求么？node11已经不受支持了啊？升级到12试一下吧，我这边升级最新依赖看一下有没有问题。

**Comment by Mister-Hope** [comment]
最新的 vue-property-decorator 把 vue-class-component 搞成了 peerDependency，我上传一个patch修一下，我本地测试手动在package.json添加这个依赖后构建是成功的。

**Comment by Mister-Hope** [comment]
```
vue-property-decorator@^8.1.1:
  version "8.4.2"
  resolved "https://registry.yarnpkg.com/vue-property-decorator/-/vue-property-decorator-8.4.2.tgz#016e17f259f73bc547e77a50ce282ba18db4ee41"
  integrity sha512-IqbARlvgPE2pzKfbecKxsu2yEH0Wv7hfHR6m4eZA3LTnNw9hveAX77vDfLFyTeMISS5N7Kucp/xRSHjcQ6bAfQ==
  dependencies:
    vue-class-component "^7.1.0"
```

```

vue-property-decorator@^8.1.1:
  version "8.5.0"
  resolved "https://registry.yarnpkg.com/vue-property-decorator/-/vue-property-decorator-8.5.0.tgz#9af64c5301413f4732640cc0d046879417e64994"
  integrity sha512-0RueJN/shPWf5gM8GLUD6bYiXr+q7bu+S1tgr7XwgBSng10H5DLQjVYfJ5XHAOPFo7fBfY1nxljBQ95qryAiWg==
```

坑我，这都不调版本号

**Comment by JQiue** [comment]
欧巴，我说咋回事，即使升级了node也卡住

**Comment by Mister-Hope** [comment]
已追踪到了 https://github.com/kaorun343/vue-property-decorator/issues/324 并且在上游插件开了一个 [issue](https://github.com/vuepress/vuepress-community/issues/49) 通知这个 breaking changes。

我临时发布了 0.6.8修复了这个问题，template 也更新了一下，现在应该正常了。

哦对每次升级之后第一次构建很慢是正常的，typescript的一些缓存文件需要在第一次生成。

**Comment by JQiue** [comment]
好吧，我又测试了以下，的确是我node版本低了，现在我跑起来了，但是页面出现了你描述的错误，hhh

**Comment by Mister-Hope** [comment]
> 好吧，我又测试了以下，的确是我node版本低了，现在我跑起来了，但是页面出现了你描述的错误，hhh

0.6.8应该正常了
